---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
namespace: "readarr"
namePrefix: "readarr-"
configMapGenerator:
  - name: app-config
    envs:
      - "app_config.env"
